container: "singularity/cns_AUMC_pipeline_v2.2.sif" # Specify container path relative to container

#Configure default resources
threads:
  sturgeon: 10
  qdnaseq_ace: 8
  pseudotime: 10

#Do not change references or timecourse definitions!
references:
  sturgeon_probes: "reference/probes/probelocs_chm13.bed"
  sturgeon_model: "reference/models/general.zip"
  qdnaseq_bins: "reference/bins/T2T.500kbp.SR50.rda"
  genome_fasta: "reference/genome/chm13v2.0.fa.gz"
  bins_export: "reference/bins_export.bed"
  chm13_bins_rds: "reference/bins/chm13_v2.0_bins.rds"
  cnv_gene_bed: "reference/genes/relevant_genes_with_chm13v2_500kb_bin_nrs_fusions_singlebin.bed"
  color_translation: "scripts/color_translation.rds"
  mgmt_model: "scripts/mgmt_137sites_mean_model.Rdata"
  mgmt_bed: "scripts/mgmt_promoter_coordinates_T2T.bed"
  report_logo: "scripts/logo.png"
  report_header: "scripts/logo.tex"

timecourse:
  bins: [5, 10, 15, 20, 30, 45, 60, 90, 120, 180, 240, 360, 480, 720, 960, 1200, 
        1440]
  cnv_bins: [30, 45, 60, 90, 120, 180, 240, 360, 480, 720, 960, 1200, 1440]
  cleanup_bins: true
  cleanup_read_lists: true

###########################################################
#Only change sample info below
###########################################################
samples:
  EMC_1:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_1.bam"
    barcode_label: "barcode02"
  EMC_2:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_2.bam"
    barcode_label: "barcode03"
  EMC_3:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_3.bam"
    barcode_label: "barcode05"
  EMC_4:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_4.bam"
    barcode_label: "barcode02"
  EMC_5:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_5.bam"
    barcode_label: "barcode03"
  EMC_6:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_6.bam"
    barcode_label: "barcode03"
  EMC_7:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_7.bam"
    barcode_label: "barcode03"
  EMC_8:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_8.bam"
    barcode_label: "barcode04"
  EMC_9:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_9.bam"
    barcode_label: "barcode04"
  EMC_10:
    bam: "/net/beegfs/users/P092309/Sturgeon_AUMC_pipeline_snakemake_v2/input/EMC_10.bam"
    barcode_label: "barcode02"